name: test

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Cargo build - Only chrono (default features)
      - uses: actions-rs/cargo@v1
        with:
          command: build

      # Cargo build - Only time
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features=time

      # Cargo build - No features
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features

      # Cargo build - All features
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

      # Test time crate
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features=time

      # Test chrono
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features=chrono
